# Generated by Django 4.2.4 on 2023-08-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackingData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("vehicleid", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
                ("coordinate_longitude", models.FloatField()),
                ("coordinate_latitude", models.FloatField()),
                ("event_description", models.CharField(max_length=100)),
                ("speed", models.IntegerField()),
                ("heading", models.IntegerField()),
                ("ignitionState", models.CharField(max_length=25)),
                ("gps_accuracy", models.IntegerField()),
                ("gps_fix_type", models.IntegerField()),
            ],
            options={
                "verbose_name": "Tracking Data",
                "verbose_name_plural": "Tracking Data Entries",
            },
        ),
    ]
